apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nh3vq59wu-nodejs
  janus-idp.io/tekton: nh3vq59wu-nodejs
  backstage.io/kubernetes-id: nh3vq59wu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nh3vq59wu-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
