apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nh3vq59wu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nh3vq59wu-nodejs 
  name: nh3vq59wu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nh3vq59wu-nodejs 
